title: Pump-Six
tagline: A personal blog
author:
  name: dntkm
  url: https://github.com/dntkm

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Build Settings

paginate: 2

tags_path: /tags/
